### ISSUE TITLE
Authentication is unnecessary

### ISSUE THREAD

**Issue by yusuke024** [nRewik/task-check-in#1]
First of all, nicely done rub.

I have a few comments here.

First, all the endpoints used in your app don't need authentication at all ([`venues/VENUE_ID`](https://developer.foursquare.com/docs/venues/venues) and [`venues/search`](https://developer.foursquare.com/docs/venues/search)). 
You can tell by looking at the information like the one below:

![screen shot 2015-12-23 at 1 04 17 pm](https://cloud.githubusercontent.com/assets/3662104/11971842/f8675030-a975-11e5-821d-b8ae0bb7be8b.png)

You can try this CURL command in the Terminal to verify this.

```
CLIENT_ID="YOUR_CLIENT_ID"
CLIENT_SECRET="YOUR_CLIENT_SECRET"
LATLONG="13.743152,100.547673" # Lumphini
curl "https://api.foursquare.com/v2/venues/explore?client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&v=20151223&ll=${LATLONG}"
```

Second, I think the more appropriate endpoint to use in this case is [`venues/explore`](https://developer.foursquare.com/docs/venues/explore).
Please have a look at it.

**Comment by nRewik** [comment]
Didn't take a closer look at that 🤔 ~> [Add userless access](https://github.com/nRewik/task-check-in/commit/0a418dcf6f700566f83ee59a7f5423ab9a683163)

---

For `explore` vs `search`. I read about it.

![screen shot 2015-12-23 at 2 10 46 pm](https://cloud.githubusercontent.com/assets/6581089/11972467/4ce67560-a97f-11e5-8864-5d351d46112d.png)

 It depends on the situation. Because, I thought what we were asking is "Where am i right now?". 

However, I've add and switch to use `/explore`. As you know the case. ~> [Use `/explore` instead of `/search`](https://github.com/nRewik/task-check-in/commit/eb7ed06dd3ea9ea6dfa821b4b4e98203d59ec0eb)
